application:
  port: 8000
  base_url: "http://127.0.0.1"
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  api_base_url: "localhost"
  sender_email: "test@email.com"
  authorization_token: "super-duper-email-secret"
  timeout_milliseconds: 200